version: '2.1'

# USAGE (from root directory): docker-compose -f ./setup/<docker-compose>.yml up
services:

  service:
    extends:
      # relative to the position of current file.
      file: ./.dockerCompose.yml
      service: 
    image: -${DEPLOYMENT:-development}
    environment:
        DEPLOYMENT: ${DEPLOYMENT:-development}
    working_dir: /tmp/build/gulp_buildTool/
    volumes:
      - ../../setup/container/shellScript:/tmp/shellScript/
      - ../../setup/build:/tmp/build/
      - ../../distribution:/tmp/distribution/

