# Vagrant customized variables, which get included inside the vagrantfile and parsed as variables.
# choose which set of variables to use.
variableSetToBeUsed: 'default'
default:
    vagrantImage: 'ubuntu/trusty64'
    # Shell scripts folder path - which will be used to call shell scripts included in each other.
    shellScriptsFolder: './shellScripts'
    # Local project folder path to be copied to VM.
    projectSynchedFolderOnLocal: './../'
    projectSynchedFolderOnVM: '/project'
    # Path inside VM of configurations for the VM, e.g. like Ansible provisioning playbooks. 
    VMConfSynchedFolderOnVM: '/vagrant'
otherset:
    examplevariable: 'example'
    # Add other variables here
