version: '3.1'

# volumes:
#   data:
#     driver: rexray

services:

  jenkins-agent:
    # image: jenkins:2.32.1-alpine
    image: vfarcic/jenkins-swarm-agent:secrets
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master https://${JenkinsServerIP}/ -labels 'docker' -executors 5
    volumes:
        # - /mnt/datadisk-1/jenkins/workspace:/workspace
        - /workspace:/workspace
        # We mounted Docker socket. As a result, any command sent to the Docker client running inside the container will run against Docker Engine on the host (in this case Docker Machine). As a result, we’ll avoid pitfalls that could be created by running Docker inside Docker (DinD)
        # Agent will run containers and use the Docker engine of the vm machine its on to do so.
        - /var/run/docker.sock:/var/run/docker.sock
        # We also mounted the host (laptop) directory that contains the keys. That will allow us to send requests to engines running inside the other cluster.
        # if we have 'cd cluster' with jenkins agent nodes & prod-like nodes, with another cluster 'production cluster' that will serve as local producation simulation (replacing the cloud hosted vm).
        - ${HOME}/.docker/machine/machines:/machines
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      mode: global

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
