version: '3'

networks:
  proxy_default:
    external: true

# volumes:
#   data:
#     driver: rexray

services:

  jenkins:
    image: jenkins:latest
    # OR use extra visual interface by BlueOcean
    # image: jenkinsci/blueocean:latest
    ports:
      - 50000:50000
    environment:
      # - JENKINS_OPTS="--prefix=/jenkins"
      - JENKINS_OPTS="--prefix=/"
    networks:
      - proxy_default
    volumes:
      - /mnt/datadisk-1/jenkins:/var/jenkins_home
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080