- name: Directory is created
  file:
    path: /data/consul-template
    state: directory
  tags: [consul-template]

- name: File is copied
  copy:
    src: consul-template
    dest: /usr/local/bin/consul-template
    mode: 0755
  tags: [consul-template]

- name: Example template is copied
  copy:
    src: "{{ item }}"
    dest: "/data/consul-template/{{ item }}"
    mode: 0644
  with_items:
    - example.ctmpl
    - example2.ctmpl
  tags: [consul-template]
