version: "3"

networks:
  default:
    external: false
    driver: overlay

# volumes:
  # data:
  #   driver: rexray
  #   driver_opts:
  #     size: "100"
  #     volumetype: "pd-ssd"
  # data:
  #   external: true

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - default
    volumes:
      - "/mnt/datadisk-1/dockerFlowProxy/haproxyConfiguration:/cfg/"
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIF_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIF_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]