version: '2.1'

# USAGE (from root directory): docker-compose -f <filePath> up <service>
services:
    
    deploymentEnvironment: # used as image, not meant to be run.
        build:
            context: ../../
            dockerfile: ./setup/container/deploymentEnvironment.dockerfile
        image: deployment-environment-yeoman
        volumes:
            - ../../source:/app/
            - ../../volume:/tmp/volume/
            - ../../setup/container/shellScript:/tmp/shellScript/
        entrypoint: /tmp/shellScript/entrypoint.sh
        # command: bash -c ""
