version: '3.7'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always # always restart even after docker restart
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: ["--no-auth"] # disbale internal password mechanism that is used by portainer for extra security. i.e. no required password for logging into admin interface.

volumes:
  portainer_data: # named volume is created in the contaxt of Docker directory of the host filesystem. 
