- name: Container is running
  docker:
    name: elasticsearch
    image: elasticsearch:2
    state: running
    ports:
      - 9200:9200
    volumes:
      /data/elasticsearch:/usr/share/elasticsearch/data
  tags: [elasticsearch]
