- name: Directory is created
  file:
    path: /data/{{ service_name }}
    recurse: yes
    state: directory
  tags: [service]

- name: Files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ files }}"
  tags: [service]

- name: Containers are pulled
  shell: docker-compose pull app
  args:
    chdir: /data/{{ service_name }}
  tags: [service]

- name: Containers are running
  shell: docker-compose up -d app
  args:
    chdir: /data/{{ service_name }}
  tags: [service]

- name: Proxy is configured
  shell: consul-template \
    -consul localhost:8500 \
    -template "{{ ct_src }}:{{ ct_dest }}:{{ ct_cmd }}" \
    -once
  tags: [service]
