repos:
  - http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
  - http://archive.cloudera.com/cdh4/one-click-install/redhat/6/x86_64/cloudera-cdh-4-0.x86_64.rpm

packages:
  - mesos
  - device-mapper-event-libs
  - git

master_packages:
  - marathon
  - zookeeper
  - zookeeper-server
  - golang
  - bind-utils
  - chronos

master_services:
  - zookeeper-server
  - mesos-master
  - marathon
  - chronos

master_templates: [
  {
    src: "resolv.conf",
    dest: "/etc/resolv.conf"
  }, {
    src: "config.json",
    dest: "/opt/go/src/github.com/mesosphere/mesos-dns/config.json"
  }
]

master_files: [
  { src: "install-dns.sh", dest: "/opt/install-dns.sh", mode: "0755" },
  { src: "sample-web-app.json", dest: "/data/mesos/sample-web-app.json", mode: "0644" }
]

mesos_apps:
  - sample-web-app.json
  - dns-app.json