version: '2.1'

# USAGE (from root directory): docker-compose -f <filePath> up <service>
services:
    
    deploymentEnvironment: # used as image, not meant to be run.
        build: # change context to project's root folder.
            context: ./
            dockerfile: ./deploymentEnvironment.dockerfile
        image: deployment-environment # name of biult image cannot be uppercase.
        # command: bash -c "sleep 100000"

    # for testing purposes - to check if all commands exist:
    deploymentEnvironmentImage:
        image: myuserindocker/deployment-environment:latest
        command: bash -c "sleep 100000"
