version: "3"

networks:
  default:
    external: false
    driver: overlay

# volumes:
  # data:
  #   driver: rexray
  #   driver_opts:
  #     size: "100"
  #     volumetype: "pd-ssd"
  # data:
  #   external: true

services:

  proxy:
    image: myuserindocker/redbird-reverseproxy:latest
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    networks:
      - default
    volumes:
      - "/mnt/datadisk-1/redbirdProxy/server:/app/server/"
      - "/mnt/datadisk-1/redbirdProxy/certificate:/app/certificate/"
    deploy:
      replicas: 1
    environment:
      DEPLOYMENT: production
      EMAIL: ${EMAIL}
      LETSENCRYPT_PORT: ${LETSENCRYPT_PORT}
    working_dir: /app/
    # command: bash -c "npm install; node entrypoint.js"

  # swarm-listener:
  #   image: vfarcic/docker-flow-swarm-listener
  #   networks:
  #     - default
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - DF_NOTIF_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
  #     - DF_NOTIF_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]