logs_dir: /data/consul/logs
config_dir: /data/consul/config
data_dir: /data/consul/data
scripts_dir: /data/consul/scripts

directories:
  - "{{ data_dir }}"
  - "{{ config_dir }}"
  - "{{ scripts_dir }}"
  - "{{ logs_dir }}"

files: [
  { src: 'consul', dest: '/usr/local/bin/consul', mode: '0755' },
  { src: 'consul_check.json', dest: '{{ config_dir }}/consul_check.json', mode: '0644' },
  { src: 'mem.sh', dest: '{{ scripts_dir }}/mem.sh', mode: '0755' },
  { src: 'disk.sh', dest: '{{ scripts_dir }}/disk.sh', mode: '0755' }
]

templates: [
  { src: 'watches.json', dest: '{{ config_dir }}/watches.json', mode: '0644'},
  { src: 'manage_watches.sh', dest: '{{ scripts_dir }}/manage_watches.sh', mode: '0755' },
  { src: 'rtime_up.sh', dest: '{{ scripts_dir }}/rtime_up.sh', mode: '0755' },
  { src: 'rtime_down.sh', dest: '{{ scripts_dir }}/rtime_down.sh', mode: '0755' }
]