- name: Packages are present
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - rsyslog
    - logrotate
  tags: [rsyslog]

- name: Config file is present
  template:
    src: 10-logstash.conf
    dest: /etc/rsyslog.d/10-logstash.conf
  register: config_result
  tags: [rsyslog]

- name: Service is restarted
  shell: service rsyslog restart
  when: config_result.changed
  tags: [rsyslog]
