version: '2.1'
# Tests & Build: source code --> distribution code

# USAGE (from root directory): docker-compose -f <filePath> up <service>
services:
    
    proxy: # used as image, not meant to be run.
        build: # change context to project's root folder.
            context: ../../
            dockerfile: ./setup/container/proxy.dockerfile
        image: myuserindocker/redbird-reverseproxy:latest # name of biult image cannot be uppercase.
        ports:
            - 80:80
            - 443:443
        environment:
            DEPLOYMENT: ${DEPLOYMENT:-production}
        volumes:
          - ../../source:/app/
        working_dir: /app/
        command: bash -c "npm install; npm update; node proxy.js"
